Move BaseSyntaxPlugin out of syntax folder
To prevent weird duplicate class errors

PHP Fatal error:  Cannot declare class dokuwiki\\plugin\\htmlok\\syntax\\BaseSyntaxPlugin,
because the name is already in use in /usr/share/dokuwiki/lib/plugins/htmlok/syntax/BaseSyntaxPlugin.php on line 0
Stack trace:
  1. {main}() /usr/share/dokuwiki/doku.php:0
  2. act_dispatch() /usr/share/dokuwiki/doku.php:126
  3. include() /usr/share/dokuwiki/inc/actions.php:27
  4. tpl_content() /usr/share/dokuwiki/lib/tpl/dokuwiki/main.php:59
  5. dokuwiki\\Extension\\Event::createAndTrigger() /usr/share/dokuwiki/inc/template.php:85
  6. dokuwiki\\Extension\\Event->trigger() /usr/share/dokuwiki/inc/Extension/Event.php:199
  7. call_user_func_array:{/usr/share/dokuwiki/inc/Extension/Event.php:133}() /usr/share/dokuwiki/inc/Extension/Event.php:133
  8. tpl_content_core() /usr/share/dokuwiki/inc/Extension/Event.php:133
	/usr/share/dokuwiki/lib/plugins/htmlok/syntax/BaseSyntaxPlugin.php
	E_COMPILE_ERROR: Cannot declare class dokuwiki\plugin\htmlok\syntax\BaseSyntaxPlugin, because the name is already in use
  #0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
  #1 {main}